version: '3.8'

services:
  nexamoda-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexamoda-app
    ports:
      - "8090:80"
    restart: unless-stopped
    networks:
      - nexamoda-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Volumen para desarrollo en tiempo real (comentar en producci√≥n)
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "com.nexamoda.description=NexaModa Web Application"
      - "com.nexamoda.version=1.0.0"

networks:
  nexamoda-network:
    driver: bridge
    name: nexamoda-net
