version: '3.8'

services:
  nexamoda-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexamoda-app
    restart: unless-stopped
    networks:
      - nexamoda-network
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  nginx-proxy:
    image: nginx:alpine
    container_name: nexamoda-proxy
    ports:
      - "8090:80"
      - "8443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    networks:
      - nexamoda-network
    depends_on:
      - nexamoda-web

  certbot:
    image: certbot/certbot
    container_name: nexamoda-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - nexamoda-network

networks:
  nexamoda-network:
    driver: bridge
    name: nexamoda-net
